name: Puzzle Check with Manual Override
on:
  workflow_dispatch:  # Manual trigger (any day)
  schedule:
    - cron: '45 20 * * 1-5'  # Auto 4:45 PM EDT Mon-Fri only

jobs:
  puzzle-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests pytz

    - name: Pull latest changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull --ff-only

    - name: Check for updates
      env:
        TZ: America/New_York
      run: |
        for attempt in {1..20}; do
          output=$(python fetch_puzzle.py 2>&1)
          exit_code=$?
          
          if [ $exit_code -eq 0 ]; then
            echo "✅ New solution found"
            echo "$output"
            exit 0
          fi
          
          if [ $exit_code -eq 2 ]; then
            echo "❌ Critical failure:"
            echo "$output"
            exit 1
          fi

          if [ $attempt -eq 20 ]; then
            echo "⚠️ No update after 20 attempts"
            echo "Last check: $(date '+%H:%M:%S')"
          fi
          
          sleep 60
        done

    - name: Commit and push
      if: success()
      run: |
        git add data.json past-solutions.json
        git diff --quiet && git diff --staged --quiet || \
          (git commit -m "Auto-update solution [skip ci]" && git push)