name: Puzzle Check
on:
  workflow_dispatch:
  schedule:
    - cron: '30 20 * * 1-5'
    - cron: '30 21 * * 1-5'

jobs:
  puzzle-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests pytz

    - name: Pull latest changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull --ff-only

    - name: Inject cache-buster
      run: |
        TIMESTAMP=$(date +%s)
        sed -i "s/__VERSION__/$TIMESTAMP/g" index.html
        sed -i "s/__VERSION__/$TIMESTAMP/g" style.css
        sed -i "s/__VERSION__/$TIMESTAMP/g" update.js
        # Verify changes
        echo "Modified files:"
        git diff
        
    - name: Check for solution updates
      env:
        TZ: America/New_York
      id: check
      run: |
        set +e
        
        for attempt in {1..60}; do
          output=$(python fetch_puzzle.py 2>&1)
          exit_code=$?
          
          case $exit_code in
            0)
              if [[ "$output" == "Updated:"* ]]; then
                echo "::set-output name=needs_commit::true"
                echo "✅ $output"
              else
                echo "ℹ️ $output"
              fi
              exit 0
              ;;
            1)
              if [ $attempt -eq 60 ]; then
                echo "🟡 No update after 60 attempts"
                exit 0
              fi
              echo "⏳ Attempt $attempt/60 - Retrying..."
              sleep 60
              ;;
            *)
              echo "❌ Critical failure: $output"
              exit 1
              ;;
          esac
        done

    - name: Commit and push changes
      if: steps.check.outputs.needs_commit == 'true'
      run: |
        git add data.json past-solutions.json index.html style.css update.js
        git commit -m "Auto-update puzzle solution [skip ci]"
        git push
