name: Puzzle Check
on:
  workflow_dispatch:
  schedule:
    - cron: '30 20 * * 1-5'  # Runs at 20:30 UTC (4:30 PM EDT, 3:30 PM EST)
    - cron: '30 21 * * 1-5'  # Runs at 21:30 UTC (5:30 PM EDT, 4:30 PM EST)

jobs:
  puzzle-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests pytz

    - name: Pull latest changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull --ff-only

    - name: Check for solution updates
      env:
        TZ: America/New_York
      run: |
        set +e  # Disable automatic error exit
        
        for attempt in {1..60}; do
          output=$(python fetch_puzzle.py 2>&1)
          exit_code=$?
          
          case $exit_code in
            0)
              echo "✅ New solution found"
              echo "$output"
              exit 0
              ;;
            1)
              if [ $attempt -eq 60 ]; then
                echo "🟡 No update after 60 attempts"
                exit 0  # Success exit for max retries
              fi
              echo "⏳ Attempt $attempt/60 - Retrying in 60 seconds..."
              sleep 60
              ;;
            *)
              echo "❌ Critical failure:"
              echo "$output"
              exit 1
              ;;
          esac
        done

    - name: Commit and push changes
      if: success()
      run: |
        git add data.json past-solutions.json
        git diff --quiet && git diff --staged --quiet || \
          (git commit -m "Auto-update puzzle solution [skip ci]" && git push)
