name: Check Puzzle Solution
on:
  workflow_dispatch:
  schedule:
    - cron: '17 17 * * 1-5'  # 5:17 PM ET (minute 17, hour 17)
      timezone: 'America/New_York'

jobs:
  check-solution:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for committing/pushing changes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Fetch all commit history

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests pytz

    - name: Fetch puzzle data
      env:
        TZ: America/New_York  # Explicitly set timezone for the script
        GITHUB_EVENT_NAME: ${{ github.event_name }}
      run: python fetch_puzzle.py

    - name: Pull latest changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git fetch --all
        git pull origin ${{ github.ref }}

    - name: Commit and push changes
      run: |
        git add data.json past-solutions.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update puzzle data [skip ci]" && git push)