name: Check Puzzle Solution
on:
  workflow_dispatch:
  schedule:
    # Checks every minute from 4:59 PM to 5:03 PM ET (Monday-Friday)
    - cron: '59 20 * * 1-5'  # 4:59 PM ET (20:59 UTC)
    - cron: '0-3 21 * * 1-5'  # 5:00-5:03 PM ET (21:00-21:03 UTC)

jobs:
  check-solution:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install requests pytz

    - name: Fetch puzzle data
      run: python fetch_puzzle.py || echo "Continuing despite non-critical error"
      env:
        TZ: America/New_York

    - name: Check for changes
      id: changes
      run: |
        git status -s
        echo "changed=$(git status -s | wc -l | xargs)" >> $GITHUB_OUTPUT

    - name: Commit and push changes
      if: steps.changes.outputs.changed != '0'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data.json
        git commit -m "Update puzzle data [skip ci]"
        git push
