name: Check Puzzle Solution
on:
  workflow_dispatch:
  schedule:
    - cron: '50-59/3 21 * * 1-5'  # 4:50-4:59 PM ET (Mon-Fri)
    - cron: '0-20/3 22 * * 1-5'    # 5:00-5:20 PM ET (Mon-Fri)

jobs:
  check-solution:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install requests pytz

    - name: Fetch puzzle data
      run: python fetch_puzzle.py
      env:
        TZ: America/New_York

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data.json index.html
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update puzzle data [skip ci]"; git push --force)
