name: Puzzle Check
on:
  workflow_dispatch:
  schedule:
    - cron: '30 20 * * 1-5'

jobs:
  puzzle-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests pytz

    - name: Pull latest changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull --ff-only

    - name: Inject cache-buster
      run: |
        TIMESTAMP=$(date +%s)
        sed -i "s/__VERSION__/$TIMESTAMP/g" index.html
        sed -i "s/__VERSION__/$TIMESTAMP/g" style.css
        sed -i "s/__VERSION__/$TIMESTAMP/g" update.js
        echo "Modified files:"
        git diff

    - name: Check for solution updates
      env:
        TZ: America/New_York
      id: check
      run: |
        set +e
        
        for attempt in {1..360}; do
          output=$(python -W ignore fetch_puzzle.py 2>warnings.log)
          exit_code=$?
          warnings=$(cat warnings.log)
          
          if [[ "$warnings" == *"Updated:"* ]]; then
            echo "needs_commit=true" >> $GITHUB_OUTPUT
            echo "✅ Update found"
            exit 0
          fi
          
          case $exit_code in
            0)
              if [[ "$output" == *"Updated:"* ]]; then
                echo "needs_commit=true" >> $GITHUB_OUTPUT
                echo "✅ $output"
                exit 0
              else
                echo "ℹ️ $output"
                exit 0
              fi
              ;;
            1)
              if [ $attempt -eq 360 ]; then
                echo "🟡 No update after 360 attempts"
                exit 0
              fi
              echo "⏳ Attempt $attempt/360 - Retrying..."
              sleep 60
              ;;
            *)
              echo "❌ Critical failure:"
              echo "$warnings"
              exit 1
              ;;
          esac
        done

    - name: Commit and push changes
      if: ${{ steps.check.outputs.needs_commit == 'true' }}
      run: |
        git add data.json past-solutions.json
        git commit -m "Auto-update puzzle solution [skip ci]"
        git push
