name: Check Puzzle Solution
on:
  workflow_dispatch:
  schedule:
    - cron: '0-5 22 * * 1-5'  # 5:00-5:05 PM ET
      timezone: 'America/New_York'

jobs:
  check-solution:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to commit changes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install requests pytz

    - name: Fetch puzzle data
      env:
        TZ: America/New_York
        GITHUB_EVENT_NAME: ${{ github.event_name }}
      run: python fetch_puzzle.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add data.json past-solutions.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update puzzle data [skip ci]" && git pull --rebase && git push)
