name: Check Puzzle Solution
on:
  workflow_dispatch:
  schedule:
    - cron: '59 20 * * 1-5'
    - cron: '0-3 21 * * 1-5'

jobs:
  check-solution:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install requests pytz

    - name: Fetch puzzle data
      env:
        TZ: America/New_York
        GITHUB_EVENT_NAME: ${{ github.event_name }}
      run: python fetch_puzzle.py || echo "Non-critical exit"

    - name: Check for changes
      id: changes
      run: |
        git status -s
        echo "changed=$(git status -s | wc -l | xargs)" >> $GITHUB_OUTPUT

    - name: Commit and push changes
      if: steps.changes.outputs.changed != '0'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data.json past-solutions.json
        git commit -m "Update puzzle data [skip ci]"
        git push
