name: Check Puzzle Solution
on:
  workflow_dispatch:
  schedule:
    # Runs every 3 minutes between 21:50 and 22:20 UTC (4:50 PM - 5:20 PM ET)
    - cron: '50-59/3 21 * * 1-5'
    - cron: '0-20/3 22 * * 1-5'

jobs:
  check-solution:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies  # Add this new step
      run: pip install requests
        
    - name: Fetch puzzle data
      run: |
        python fetch_puzzle.py
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update puzzle data"; git push)
