name: Puzzle Check
on:
  workflow_dispatch:
  schedule:
    - cron: '55 21 * * 1-5'  # 4:45 PM EDT (20:45 UTC) Mon-Fri

jobs:
  puzzle-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests pytz

    - name: Pull latest changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull --ff-only

    - name: Check for solution updates
      env:
        TZ: America/New_York
      run: |
        for attempt in {1..20}; do
          output=$(python fetch_puzzle.py 2>&1)
          exit_code=$?
          
          # Success - new solution found
          if [ $exit_code -eq 0 ]; then
            echo "✅ New solution found"
            echo "$output"
            exit 0
          fi

          # Retry case - same solution
          if [ $exit_code -eq 1 ]; then
            if [ $attempt -eq 20 ]; then
              echo "🟡 No update after 20 attempts"
              exit 0  # Graceful exit
            fi
            echo "⏳ Attempt $attempt/20 - No changes"
            sleep 60
            continue
          fi

          # Fatal error
          echo "❌ Critical failure:"
          echo "$output"
          exit 1
        done

    - name: Commit and push changes
      if: success()
      run: |
        git add data.json past-solutions.json
        git diff --quiet && git diff --staged --quiet || \
          (git commit -m "Auto-update puzzle solution [skip ci]" && git push)
