name: Check Puzzle Solution
on:
  workflow_dispatch:
  schedule:
    - cron: '45 21 * * *'  # 4:45 PM ET (EST, UTC-5) during Standard Time
    - cron: '45 20 * * *'  # 4:45 PM ET (EDT, UTC-4) during Daylight Saving Time
jobs:
  check-solution:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for git commits/pushes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Get full git history

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests pytz

    - name: Fetch puzzle data with retry
      env:
        TZ: America/New_York  # Ensure script uses ET
        GITHUB_EVENT_NAME: ${{ github.event_name }}
      run: |
        for attempt in {1..20}; do
          python fetch_puzzle.py
          if [ $? -eq 0 ]; then
            echo "✅ Data found on attempt $attempt"
            exit 0
          fi
          echo "⏳ No data available (attempt $attempt/20). Retrying in 60 seconds..."
          sleep 60
        done
        echo "❌ No data found after 20 attempts"
        exit 1

    - name: Pull latest changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git fetch --all
        git pull origin ${{ github.ref }}

    - name: Commit and push changes
      run: |
        git add data.json past-solutions.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update puzzle data [skip ci]" && git push)
